<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RuntimeIdentifiers Condition="'$(MSBuildProjectName)' == 'XiaobianPet'">win-x64</RuntimeIdentifiers>
    <RuntimeFrameworkVersion Condition="'$(MSBuildProjectName)' == 'XiaobianPet'">9.0.20</RuntimeFrameworkVersion>
    <PathMap>$(MSBuildThisFileDirectory)=/_/</PathMap>
    <DebugType Condition="'$(Configuration)' == 'Release'">None</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
  </PropertyGroup>
</Project>
